spring.application.name=welcome-app
server.servlet.context-path=/${spring.application.name}
server.port=8080

#To enable swagger
springdoc.api-docs.path=/v1/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
# Show API request duration
springdoc.swagger-ui.displayRequestDuration=true

spring.config.import=vault://
# For local
spring.cloud.vault.uri=http://127.0.0.1:8200
# For docker
#spring.cloud.vault.uri=http://host.docker.internal:8200
spring.cloud.vault.token=${VAULT_TOKEN}
# KV Engine
spring.cloud.vault.kv.enabled=true
# Your mount name
spring.cloud.vault.kv.backend=kv-dev
# Your secret path
spring.cloud.vault.kv.default-context=rabbitmq-dev

# RabbitMQ Queue Configuration
rabbitmq.queues=my_queue,rmq_test,samrat_dharm

# RabbitMQ Consumer Configuration
rabbitmq.consumer.prefetch-count=1
rabbitmq.consumer.auto-ack=false
rabbitmq.consumer.processing-delay-multiplier=100

# RabbitMQ Producer Configuration
rabbitmq.producer.message-interval-ms=2000
rabbitmq.producer.publisher-confirm-timeout-ms=5000
rabbitmq.producer.enable-publisher-confirms=true
rabbitmq.producer.message-template=Hello RMQ how are you : {messageId}

# RabbitMQ Queue Configuration
rabbitmq.queue.durable=true
rabbitmq.queue.exclusive=false
rabbitmq.queue.auto-delete=false