spring.application.name=welcome-app
server.servlet.context-path=/${spring.application.name}
server.port=8080

#To enable swagger
springdoc.api-docs.path=/v1/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
# Show API request duration
springdoc.swagger-ui.displayRequestDuration=true

spring.config.import=vault://
spring.cloud.vault.uri=http://127.0.0.1:8200
spring.cloud.vault.token=${VAULT_TOKEN}
# KV Engine
spring.cloud.vault.kv.enabled=true
# Your mount name
spring.cloud.vault.kv.backend=kv-dev
# Your secret path
spring.cloud.vault.kv.default-context=rabbitmq-dev