apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome
  namespace: ${{ inputs.NAMESPACE }}
  labels:
    app: welcome
  annotations:
    description: "Welcome application deployment"
    maintained-by: "devops-team"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome
  template:
    metadata:
      labels:
        app: welcome
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: welcome
          image: ghcr.io/rajmcaitm/welcome/welcome:${APP_VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: welcome-config
#          livenessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#            initialDelaySeconds: 60
#            periodSeconds: 10
#            timeoutSeconds: 5
#            failureThreshold: 3
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#            initialDelaySeconds: 30
#            periodSeconds: 5
#            timeoutSeconds: 3
#            failureThreshold: 3
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
      imagePullSecrets:
        - name: ghcr-secret
